In [ ]:
import sqlite3
import pandas as pdd4e      azzs

con = sqlite3.connect("../data/raw/ipl.db")

def q(sql):
    return pd.read_sql(sql, con)

In [2]:
q("SELECT COUNT(*) FROM matches;")

   COUNT(*)
0      1212

In [3]:
# Part A - Question 1
q("""
SELECT *
FROM teams;
""")

# My observation:
# SELECT * displays all columns and rows from the teams table.

    team_id                    team_name
0         1  Royal Challengers Bangalore
1         2          Sunrisers Hyderabad
2         3               Mumbai Indians
3         4       Rising Pune Supergiant
4         5                Gujarat Lions
5         6        Kolkata Knight Riders
6       129          Chennai Super Kings
7       134             Rajasthan Royals
8       252               Delhi Capitals
9       494                 Punjab Kings
10      614         Lucknow Super Giants
11      615               Gujarat Titans
12     1068              Deccan Chargers
13     1414         Kochi Tuskers Kerala
14     1419                Pune Warriors
15     3604      Rising Pune Supergiants

In [4]:
# Part A - Question 2
q("""
SELECT *
FROM deliveries
LIMIT 10;
""")

# My observation:
# LIMIT 10 displays only the first 10 rows from the deliveries table.

,season_id,match_id,batter,bowler,non_striker,over_number,ball_number,batter_runs,extras,total_runs,...,leg_bye_runs,bye_runs,penalty_runs,wicket_kind,is_super_over,innings,batting_team_id,bowling_team_id,batting_team,bowling_team
0,2008,335982,SC Ganguly,P Kumar,BB McCullum,0,0,0,1,1,...,1,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
1,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,1,0,0,0,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
2,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,2,0,1,1,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
3,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,3,0,0,0,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
4,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,4,0,0,0,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
5,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,5,0,0,0,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
6,2008,335982,BB McCullum,P Kumar,SC Ganguly,0,6,0,1,1,...,1,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
7,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,0,0,0,0,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
8,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,1,4,0,4,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore
9,2008,335982,BB McCullum,Z Khan,SC Ganguly,1,2,4,0,4,...,0,0,0,None,0,1,6,1,Kolkata Knight Riders,Royal Challengers Bangalore

In [5]:
# Part A - Question 3
q("""
SELECT match_id, season, match_winner, result
FROM matches;
""")

# My observation:
# This query displays only the selected columns from the matches table.

      match_id season                 match_winner result
0       335982   2008        Kolkata Knight Riders    win
1      1082591   2017          Sunrisers Hyderabad    win
2      1082592   2017       Rising Pune Supergiant    win
3      1082593   2017        Kolkata Knight Riders    win
4      1082594   2017                 Punjab Kings    win
...        ...    ...                          ...    ...
1207   1529282   2026  Royal Challengers Bangalore    win
1208   1529283   2026             Rajasthan Royals    win
1209   1529284   2026          Sunrisers Hyderabad    win
1210   1529285   2026               Gujarat Titans    win
1211   1529286   2026               Delhi Capitals    win

[1212 rows x 4 columns]

In [6]:
# Part A - Question 4
q("""
SELECT DISTINCT season
FROM matches;
""")

# My observation:
# DISTINCT shows each season only once.

     season
0      2008
1      2009
2      2010
3      2011
4      2012
5      2013
6      2014
7      2015
8      2016
9      2017
10     2018
11     2019
12  2020/21
13     2021
14     2022
15     2023
16     2024
17     2025
18     2026

In [7]:
# Part A - Question 5
q("""
SELECT DISTINCT city
FROM matches;
""")

# My observation:
# DISTINCT shows each city only once.

              city
0        Bangalore
1        Hyderabad
2             Pune
3           Rajkot
4           Indore
5        Bengaluru
6           Mumbai
7          Kolkata
8            Delhi
9       Chandigarh
10          Kanpur
11         Chennai
12          Jaipur
13   Visakhapatnam
14       Abu Dhabi
15             NaN
16       Ahmedabad
17         Sharjah
18           Dubai
19     Navi Mumbai
20         Lucknow
21        Guwahati
22      Dharamsala
23          Mohali
24       Cape Town
25  Port Elizabeth
26          Durban
27       Centurion
28     East London
29    Johannesburg
30       Kimberley
31    Bloemfontein
32         Cuttack
33          Nagpur
34           Kochi
35          Raipur
36          Ranchi
37  New Chandigarh

In [8]:
# Part B - Question 1
q("""
SELECT *
FROM matches
WHERE season = 2019;
""")

# My observation:
# WHERE filters the matches and shows only matches from the 2019 season.

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,1175356,2019,6,Chennai,2019-03-23,Indian Premier League,1.0,male,T20,T20,...,Chennai Super Kings,NaN,7.0,win,Harbhajan Singh,1,129,129,129,228.0
1,1175357,2019,6,Kolkata,2019-03-24,Indian Premier League,2.0,male,T20,T20,...,Kolkata Knight Riders,NaN,6.0,win,AD Russell,2,6,6,6,1437.0
2,1175358,2019,6,Mumbai,2019-03-24,Indian Premier League,3.0,male,T20,T20,...,Delhi Capitals,37.0,NaN,win,RR Pant,252,3,3,252,181.0
3,1175359,2019,6,Jaipur,2019-03-25,Indian Premier League,4.0,male,T20,T20,...,Punjab Kings,14.0,NaN,win,CH Gayle,494,134,134,494,1.0
4,1175360,2019,6,Delhi,2019-03-26,Indian Premier League,5.0,male,T20,T20,...,Chennai Super Kings,NaN,6.0,win,SR Watson,252,129,252,129,5.0
5,1175361,2019,6,Kolkata,2019-03-27,Indian Premier League,6.0,male,T20,T20,...,Kolkata Knight Riders,28.0,NaN,win,AD Russell,6,494,494,6,1437.0
6,1175362,2019,6,Bengaluru,2019-03-28,Indian Premier League,7.0,male,T20,T20,...,Mumbai Indians,6.0,NaN,win,JJ Bumrah,3,1,1,3,33.0
7,1175363,2019,6,Hyderabad,2019-03-29,Indian Premier League,8.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,5.0,win,Rashid Khan,134,2,134,2,22.0
8,1175364,2019,6,Chandigarh,2019-03-30,Indian Premier League,9.0,male,T20,T20,...,Punjab Kings,NaN,8.0,win,MA Agarwal,3,494,494,494,35.0
9,1175365,2019,6,Delhi,2019-03-30,Indian Premier League,10.0,male,T20,T20,...,Delhi Capitals,NaN,NaN,tie,PP Shaw,6,252,252,252,1849.0
10,1175366,2019,6,Hyderabad,2019-03-31,Indian Premier League,11.0,male,T20,T20,...,Sunrisers Hyderabad,118.0,NaN,win,JM Bairstow,2,1,1,2,2719.0
11,1175367,2019,6,Chennai,2019-03-31,Indian Premier League,12.0,male,T20,T20,...,Chennai Super Kings,8.0,NaN,win,MS Dhoni,129,134,134,129,38.0
12,1175368,2019,6,Chandigarh,2019-04-01,Indian Premier League,13.0,male,T20,T20,...,Punjab Kings,14.0,NaN,win,SM Curran,494,252,252,494,2768.0
13,1175369,2019,6,Jaipur,2019-04-02,Indian Premier League,14.0,male,T20,T20,...,Rajasthan Royals,NaN,7.0,win,S Gopal,1,134,134,134,1449.0
14,1175370,2019,6,Mumbai,2019-04-03,Indian Premier League,15.0,male,T20,T20,...,Mumbai Indians,37.0,NaN,win,HH Pandya,3,129,129,3,30.0
15,1175371,2019,6,Delhi,2019-04-04,Indian Premier League,16.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,5.0,win,JM Bairstow,252,2,2,2,2719.0
16,1175372,2019,6,Bengaluru,2019-04-05,Indian Premier League,17.0,male,T20,T20,...,Kolkata Knight Riders,NaN,5.0,win,AD Russell,1,6,6,6,1437.0
17,1178393,2019,6,Chennai,2019-04-06,Indian Premier League,18.0,male,T20,T20,...,Chennai Super Kings,22.0,NaN,win,Harbhajan Singh,129,494,129,129,228.0
18,1178394,2019,6,Hyderabad,2019-04-06,Indian Premier League,19.0,male,T20,T20,...,Mumbai Indians,40.0,NaN,win,AS Joseph,3,2,2,3,3100.0
19,1178395,2019,6,Bengaluru,2019-04-07,Indian Premier League,20.0,male,T20,T20,...,Delhi Capitals,NaN,4.0,win,K Rabada,1,252,252,252,590.0
20,1178396,2019,6,Jaipur,2019-04-07,Indian Premier League,21.0,male,T20,T20,...,Kolkata Knight Riders,NaN,8.0,win,HF Gurney,134,6,6,6,3156.0
21,1178397,2019,6,Chandigarh,2019-04-08,Indian Premier League,22.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,KL Rahul,2,494,494,494,1409.0
22,1178398,2019,6,Chennai,2019-04-09,Indian Premier League,23.0,male,T20,T20,...,Chennai Super Kings,NaN,7.0,win,DL Chahar,6,129,129,129,41.0
23,1178399,2019,6,Mumbai,2019-04-10,Indian Premier League,24.0,male,T20,T20,...,Mumbai Indians,NaN,3.0,win,KA Pollard,494,3,3,3,29.0
24,1178400,2019,6,Jaipur,2019-04-11,Indian Premier League,25.0,male,T20,T20,...,Chennai Super Kings,NaN,4.0,win,MS Dhoni,134,129,129,129,38.0
25,1178401,2019,6,Kolkata,2019-04-12,Indian Premier League,26.0,male,T20,T20,...,Delhi Capitals,NaN,7.0,win,S Dhawan,6,252,252,252,13.0
26,1178402,2019,6,Mumbai,2019-04-13,Indian Premier League,27.0,male,T20,T20,...,Rajasthan Royals,NaN,4.0,win,JC Buttler,3,134,134,134,24.0
27,1178403,2019,6,Chandigarh,2019-04-13,Indian Premier League,28.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,8.0,win,AB de Villiers,494,1,1,1,245.0
28,1178404,2019,6,Kolkata,2019-04-14,Indian Premier League,29.0,male,T20,T20,...,Chennai Super Kings,NaN,5.0,win,Imran Tahir,6,129,129,129,44.0
29,1178405,2019,6,Hyderabad,2019-04-14,Indian Premier League,30.0,male,T20,T20,...,Delhi Capitals,39.0,NaN,win,KMA Paul,252,2,2,252,2745.0
30,1178406,2019,6,Mumbai,2019-04-15,Indian Premier League,31.0,male,T20,T20,...,Mumbai Indians,NaN,5.0,win,SL Malinga,1,3,3,3,230.0
31,1178407,2019,6,Chandigarh,2019-04-16,Indian Premier League,32.0,male,T20,T20,...,Punjab Kings,12.0,NaN,win,R Ashwin,494,134,134,494,1416.0
32,1178408,2019,6,Hyderabad,2019-04-17,Indian Premier League,33.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,6.0,win,DA Warner,129,2,129,2,12.0
33,1178409,2019,6,Delhi,2019-04-18,Indian Premier League,34.0,male,T20,T20,...,Mumbai Indians,40.0,NaN,win,HH Pandya,3,252,3,3,30.0
34,1178410,2019,6,Kolkata,2019-04-19,Indian Premier League,35.0,male,T20,T20,...,Royal Challengers Bangalore,10.0,NaN,win,V Kohli,1,6,6,1,332.0
35,1178411,2019,6,Jaipur,2019-04-20,Indian Premier League,36.0,male,T20,T20,...,Rajasthan Royals,NaN,5.0,win,SPD Smith,3,134,134,134,36.0
36,1178412,2019,6,Delhi,2019-04-20,Indian Premier League,37.0,male,T20,T20,...,Delhi Capitals,NaN,5.0,win,SS Iyer,494,252,252,252,389.0
37,1178413,2019,6,Hyderabad,2019-04-21,Indian Premier League,38.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,9.0,win,KK Ahmed,6,2,2,2,2662.0
38,1178414,2019,6,Bengaluru,2019-04-21,Indian Premier League,39.0,male,T20,T20,...,Royal Challengers Bangalore,1.0,NaN,win,PA Patel,1,129,129,1,23.0
39,1178415,2019,6,Jaipur,2019-04-22,Indian Premier League,40.0,male,T20,T20,...,Delhi Capitals,NaN,6.0,win,RR Pant,134,252,252,252,181.0
40,1178416,2019,6,Chennai,2019-04-23,Indian Premier League,41.0,male,T20,T20,...,Chennai Super Kings,NaN,6.0,win,SR Watson,2,129,129,129,5.0
41,1178417,2019,6,Bengaluru,2019-04-24,Indian Premier League,42.0,male,T20,T20,...,Royal Challengers Bangalore,17.0,NaN,win,AB de Villiers,1,494,494,1,245.0
42,1178418,2019,6,Kolkata,2019-04-25,Indian Premier League,43.0,male,T20,T20,...,Rajasthan Royals,NaN,3.0,win,VR Aaron,6,134,134,134,241.0
43,1178419,2019,6,Chennai,2019-04-26,Indian Premier League,44.0,male,T20,T20,...,Mumbai Indians,46.0,NaN,win,RG Sharma,3,129,129,3,25.0
44,1178420,2019,6,Jaipur,2019-04-27,Indian Premier League,45.0,male,T20,T20,...,Rajasthan Royals,NaN,7.0,win,JD Unadkat,2,134,134,134,438.0
45,1178421,2019,6,Delhi,2019-04-28,Indian Premier League,46.0,male,T20,T20,...,Delhi Capitals,16.0,NaN,win,S Dhawan,252,1,252,252,13.0
46,1178422,2019,6,Kolkata,2019-04-28,Indian Premier League,47.0,male,T20,T20,...,Kolkata Knight Riders,34.0,NaN,win,AD Russell,6,3,3,6,1437.0
47,1178423,2019,6,Hyderabad,2019-04-29,Indian Premier League,48.0,male,T20,T20,...,Sunrisers Hyderabad,45.0,NaN,win,DA Warner,2,494,494,2,12.0
48,1178424,2019,6,Bengaluru,2019-04-30,Indian Premier League,49.0,male,T20,T20,...,Rajasthan Royals,NaN,NaN,no result,,1,134,134,134,NaN
49,1178425,2019,6,Chennai,2019-05-01,Indian Premier League,50.0,male,T20,T20,...,Chennai Super Kings,80.0,NaN,win,MS Dhoni,129,252,252,129,38.0
50,1178426,2019,6,Mumbai,2019-05-02,Indian Premier League,51.0,male,T20,T20,...,Sunrisers Hyderabad,NaN,NaN,tie,JJ Bumrah,3,2,3,2,33.0
51,1178427,2019,6,Chandigarh,2019-05-03,Indian Premier League,52.0,male,T20,T20,...,Kolkata Knight Riders,NaN,7.0,win,Shubman Gill,494,6,6,6,1580.0
52,1178428,2019,6,Delhi,2019-05-04,Indian Premier League,53.0,male,T20,T20,...,Delhi Capitals,NaN,5.0,win,A Mishra,134,252,134,252,185.0
53,1178429,2019,6,Bengaluru,2019-05-04,Indian Premier League,54.0,male,T20,T20,...,Royal Challengers Bangalore,NaN,4.0,win,SO Hetmyer,2,1,1,1,2700.0
54,1178430,2019,6,Chandigarh,2019-05-05,Indian Premier League,55.0,male,T20,T20,...,Punjab Kings,NaN,6.0,win,KL Rahul,129,494,494,494,1409.0
55,1178431,2019,6,Mumbai,2019-05-05,Indian Premier League,56.0,male,T20,T20,...,Mumbai Indians,NaN,9.0,win,HH Pandya,6,3,3,3,30.0
56,1181764,2019,6,Chennai,2019-05-07,Indian Premier League,NaN,male,T20,T20,...,Mumbai Indians,NaN,6.0,win,SA Yadav,129,3,129,3,61.0
57,1181766,2019,6,Visakhapatnam,2019-05-08,Indian Premier League,NaN,male,T20,T20,...,Delhi Capitals,NaN,2.0,win,RR Pant,2,252,252,252,181.0
58,1181767,2019,6,Visakhapatnam,2019-05-10,Indian Premier League,NaN,male,T20,T20,...,Chennai Super Kings,NaN,6.0,win,F du Plessis,252,129,129,129,267.0
59,1181768,2019,6,Hyderabad,2019-05-12,Indian Premier League,NaN,male,T20,T20,...,Mumbai Indians,1.0,NaN,win,JJ Bumrah,3,129,3,3,33.0

In [9]:
# Part B - Question 2
q("""
SELECT *
FROM matches
WHERE win_by_runs > 100;
""")

# My observation:
# This query shows matches where the winning margin in runs is greater than 100.

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,335982,2008,6,Bangalore,2008-04-18,Indian Premier League,1.0,male,T20,T20,...,Kolkata Knight Riders,140.0,None,win,BB McCullum,1,6,1,6,46.0
1,1082635,2017,6,Delhi,2017-05-06,Indian Premier League,45.0,male,T20,T20,...,Mumbai Indians,146.0,None,win,LMP Simmons,252,3,252,3,1035.0
2,1136601,2018,6,Kolkata,2018-05-09,Indian Premier League,41.0,male,T20,T20,...,Mumbai Indians,102.0,None,win,Ishan Kishan,3,6,6,3,347.0
3,1175366,2019,6,Hyderabad,2019-03-31,Indian Premier League,11.0,male,T20,T20,...,Sunrisers Hyderabad,118.0,None,win,JM Bairstow,2,1,1,2,2719.0
4,1359534,2023,6,Jaipur,2023-05-14,Indian Premier League,60.0,male,T20,T20,...,Royal Challengers Bangalore,112.0,None,win,WD Parnell,1,134,1,1,8626.0
5,1422134,2024,6,Visakhapatnam,2024-04-03,Indian Premier League,16.0,male,T20,T20,...,Kolkata Knight Riders,106.0,None,win,SP Narine,6,252,6,6,65.0
6,336038,2008,6,Mumbai,2008-05-30,Indian Premier League,NaN,male,T20,T20,...,Rajasthan Royals,105.0,None,win,SR Watson,252,134,252,134,5.0
7,501260,2011,6,Dharamsala,2011-05-17,Indian Premier League,63.0,male,T20,T20,...,Punjab Kings,111.0,None,win,AC Gilchrist,494,1,494,494,12007.0
8,598027,2013,6,Bangalore,2013-04-23,Indian Premier League,31.0,male,T20,T20,...,Royal Challengers Bangalore,130.0,None,win,CH Gayle,1,1419,1419,1,1.0
9,829785,2015,6,Bangalore,2015-05-06,Indian Premier League,40.0,male,T20,T20,...,Royal Challengers Bangalore,138.0,None,win,CH Gayle,1,494,494,1,1.0
10,980987,2016,6,Bangalore,2016-05-14,Indian Premier League,44.0,male,T20,T20,...,Royal Challengers Bangalore,144.0,None,win,AB de Villiers,1,5,5,1,245.0
11,1473505,2025,6,Delhi,2025-05-25,Indian Premier League,68.0,male,T20,T20,...,Sunrisers Hyderabad,110.0,None,win,H Klaasen,2,6,2,2,1740.0
12,1529276,2026,6,Mumbai,2026-04-23,Indian Premier League,33.0,male,T20,T20,...,Chennai Super Kings,103.0,None,win,SV Samson,129,3,3,129,180.0

In [10]:
# Part B - Question 3
q("""
SELECT *
FROM matches
WHERE season = 2016 AND win_by_wickets > 5;
""")

# My observation:
# AND applies both conditions and shows 2016 matches won by more than 5 wickets.

,match_id,season_id,balls_per_over,city,match_date,event_name,match_number,gender,match_type,format,...,match_winner,win_by_runs,win_by_wickets,result,player_of_match,team1_id,team2_id,toss_winner_id,match_winner_id,player_of_match_id
0,980901,2016,6,Mumbai,2016-04-09,Indian Premier League,1.0,male,T20,T20,...,Rising Pune Supergiant,None,9.0,win,AM Rahane,3,4,3,4,34.0
1,980903,2016,6,Kolkata,2016-04-10,Indian Premier League,2.0,male,T20,T20,...,Kolkata Knight Riders,None,9.0,win,AD Russell,6,252,6,6,1437.0
2,980909,2016,6,Kolkata,2016-04-13,Indian Premier League,5.0,male,T20,T20,...,Mumbai Indians,None,6.0,win,RG Sharma,6,3,3,3,25.0
3,980911,2016,6,Rajkot,2016-04-14,Indian Premier League,6.0,male,T20,T20,...,Gujarat Lions,None,7.0,win,AJ Finch,5,4,4,5,48.0
4,980913,2016,6,Delhi,2016-04-15,Indian Premier League,7.0,male,T20,T20,...,Delhi Capitals,None,8.0,win,A Mishra,252,494,252,252,185.0
5,980915,2016,6,Hyderabad,2016-04-16,Indian Premier League,8.0,male,T20,T20,...,Kolkata Knight Riders,None,8.0,win,G Gambhir,2,6,2,6,56.0
6,980919,2016,6,Chandigarh,2016-04-17,Indian Premier League,10.0,male,T20,T20,...,Punjab Kings,None,6.0,win,M Vohra,494,4,4,494,68.0
7,980921,2016,6,Bangalore,2016-04-17,Indian Premier League,11.0,male,T20,T20,...,Delhi Capitals,None,7.0,win,Q de Kock,1,252,252,252,1421.0
8,980923,2016,6,Hyderabad,2016-04-18,Indian Premier League,12.0,male,T20,T20,...,Sunrisers Hyderabad,None,7.0,win,DA Warner,2,3,2,2,12.0
9,980925,2016,6,Chandigarh,2016-04-19,Indian Premier League,13.0,male,T20,T20,...,Kolkata Knight Riders,None,6.0,win,RV Uthappa,494,6,6,6,58.0
10,980927,2016,6,Mumbai,2016-04-20,Indian Premier League,14.0,male,T20,T20,...,Mumbai Indians,None,6.0,win,RG Sharma,3,1,3,3,25.0
11,980929,2016,6,Rajkot,2016-04-21,Indian Premier League,15.0,male,T20,T20,...,Sunrisers Hyderabad,None,10.0,win,B Kumar,5,2,2,2,20.0
12,980937,2016,6,Rajkot,2016-04-24,Indian Premier League,19.0,male,T20,T20,...,Gujarat Lions,None,6.0,win,V Kohli,5,1,1,5,332.0
13,980947,2016,6,Mumbai,2016-04-28,Indian Premier League,24.0,male,T20,T20,...,Mumbai Indians,None,6.0,win,RG Sharma,3,6,3,3,25.0
14,980957,2016,6,Pune,2016-05-01,Indian Premier League,29.0,male,T20,T20,...,Mumbai Indians,None,8.0,win,RG Sharma,4,3,3,3,25.0
15,980961,2016,6,Rajkot,2016-05-03,Indian Premier League,31.0,male,T20,T20,...,Delhi Capitals,None,8.0,win,RR Pant,5,252,252,252,181.0
16,980965,2016,6,Delhi,2016-05-05,Indian Premier League,33.0,male,T20,T20,...,Rising Pune Supergiant,None,7.0,win,AM Rahane,252,4,4,4,34.0
17,980969,2016,6,Bangalore,2016-05-07,Indian Premier League,35.0,male,T20,T20,...,Royal Challengers Bangalore,None,7.0,win,V Kohli,1,4,1,1,332.0
18,980981,2016,6,Bangalore,2016-05-11,Indian Premier League,41.0,male,T20,T20,...,Mumbai Indians,None,6.0,win,KH Pandya,1,3,3,3,28.0
19,980983,2016,6,Hyderabad,2016-05-12,Indian Premier League,42.0,male,T20,T20,...,Delhi Capitals,None,7.0,win,CH Morris,2,252,252,252,182.0
20,980985,2016,6,Visakhapatnam,2016-05-13,Indian Premier League,43.0,male,T20,T20,...,Punjab Kings,None,7.0,win,MP Stoinis,3,494,3,494,73.0
21,980989,2016,6,Kolkata,2016-05-14,Indian Premier League,45.0,male,T20,T20,...,Kolkata Knight Riders,None,8.0,win,YK Pathan,6,4,4,6,60.0
22,980991,2016,6,Chandigarh,2016-05-15,Indian Premier League,46.0,male,T20,T20,...,Sunrisers Hyderabad,None,7.0,win,HM Amla,494,2,494,2,67.0
23,980995,2016,6,Kolkata,2016-05-16,Indian Premier League,48.0,male,T20,T20,...,Royal Challengers Bangalore,None,9.0,win,V Kohli,6,1,1,1,332.0
24,981001,2016,6,Kanpur,2016-05-19,Indian Premier League,51.0,male,T20,T20,...,Gujarat Lions,None,6.0,win,DR Smith,5,6,5,5,50.0
25,981003,2016,6,Raipur,2016-05-20,Indian Premier League,52.0,male,T20,T20,...,Delhi Capitals,None,6.0,win,KK Nair,252,2,252,252,179.0
26,981007,2016,6,Kanpur,2016-05-21,Indian Premier League,54.0,male,T20,T20,...,Gujarat Lions,None,6.0,win,SK Raina,5,3,5,5,47.0
27,981011,2016,6,Raipur,2016-05-22,Indian Premier League,56.0,male,T20,T20,...,Royal Challengers Bangalore,None,6.0,win,V Kohli,252,1,1,1,332.0

In [11]:
# Part B - Question 4
q("""
SELECT match_id, win_by_runs
FROM matches
ORDER BY win_by_runs DESC
LIMIT 10;
""")

# My observation:
# DESC sorts the largest winning margins first and LIMIT returns the top 10.

   match_id  win_by_runs
0   1082635        146.0
1    980987        144.0
2    335982        140.0
3    829785        138.0
4    598027        130.0
5   1175366        118.0
6   1359534        112.0
7    501260        111.0
8   1473505        110.0
9   1422134        106.0

In [12]:
# Part B - Question 5
q("""
SELECT match_id, win_by_wickets
FROM matches
WHERE win_by_wickets IS NOT NULL
ORDER BY win_by_wickets ASC
LIMIT 10;
""")

# My observation:
# IS NOT NULL removes missing values and ASC sorts the smallest wicket margins first.

   match_id  win_by_wickets
0   1136561             1.0
1   1136567             1.0
2   1359489             1.0
3   1473441             1.0
4    829791             1.0
5   1082640             2.0
6   1136617             2.0
7   1181766             2.0
8   1254058             2.0
9   1254098             2.0

In [13]:
# Part C - Question 1
q("""
SELECT COUNT(*) AS total_matches
FROM matches;
""")

# My observation:
# COUNT(*) counts the total number of matches.

   total_matches
0           1212

In [14]:
# Part C - Question 2
q("""
SELECT COUNT(*) AS total_deliveries
FROM deliveries;
""")

# My observation:
# COUNT(*) counts all delivery records in the deliveries table.

   total_deliveries
0            288226

In [15]:
# Part C - Question 3
q("""
SELECT COUNT(DISTINCT venue) AS total_venues
FROM matches;
""")

# My observation:
# COUNT(DISTINCT venue) counts each venue only once.

   total_venues
0            59

In [16]:
# Part C - Question 4
q("""
SELECT venue, COUNT(*) AS matches_hosted
FROM matches
GROUP BY venue
ORDER BY matches_hosted DESC;
""")

# My observation:
# GROUP BY groups matches by venue and shows the venues with the most matches first.

                                                venue  matches_hosted
0                                        Eden Gardens              77
1                                    Wankhede Stadium              73
2                               M Chinnaswamy Stadium              65
3                                    Feroz Shah Kotla              60
4                            Wankhede Stadium, Mumbai              57
5           Rajiv Gandhi International Stadium, Uppal              49
6                     MA Chidambaram Stadium, Chepauk              48
7                              Sawai Mansingh Stadium              47
8                 Dubai International Cricket Stadium              46
9            MA Chidambaram Stadium, Chepauk, Chennai              38
10                   Narendra Modi Stadium, Ahmedabad              37
11         Punjab Cricket Association Stadium, Mohali              35
12                               Sheikh Zayed Stadium              29
13                            Sharjah Cricket Stadium              28
14                              Eden Gardens, Kolkata              27
15                        Arun Jaitley Stadium, Delhi              27
16  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...              26
17                   M Chinnaswamy Stadium, Bengaluru              24
18  Rajiv Gandhi International Stadium, Uppal, Hyd...              23
19            Maharashtra Cricket Association Stadium              22
20                 Dr DY Patil Sports Academy, Mumbai              20
21                     Sawai Mansingh Stadium, Jaipur              19
22                         Dr DY Patil Sports Academy              17
23                          Brabourne Stadium, Mumbai              17
24                         Subrata Roy Sahara Stadium              16
25                 Rajiv Gandhi International Stadium              15
26                              M.Chinnaswamy Stadium              15
27                                          Kingsmead              15
28                               Arun Jaitley Stadium              14
29      Maharashtra Cricket Association Stadium, Pune              13
30  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...              13
31                                    SuperSport Park              12
32                       Sardar Patel Stadium, Motera              12
33  Punjab Cricket Association IS Bindra Stadium, ...              11
34             Saurashtra Cricket Association Stadium              10
35       Punjab Cricket Association IS Bindra Stadium              10
36  Maharaja Yadavindra Singh International Cricke...              10
37                                  Brabourne Stadium              10
38                             MA Chidambaram Stadium               9
39                             Holkar Cricket Stadium               9
40       Himachal Pradesh Cricket Association Stadium               9
41                   Zayed Cricket Stadium, Abu Dhabi               8
42                              New Wanderers Stadium               8
43                Barsapara Cricket Stadium, Guwahati               8
44                                   St George's Park               7
45                                           Newlands               7
46                 JSCA International Stadium Complex               7
47                                   Barabati Stadium               7
48   Shaheed Veer Narayan Singh International Stadium               6
49  Himachal Pradesh Cricket Association Stadium, ...               6
50  Punjab Cricket Association IS Bindra Stadium, ...               5
51                                      Nehru Stadium               5
52  Maharaja Yadavindra Singh International Cricke...               5
53                                         Green Park               4
54  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...               4
55       Vidarbha Cricket Association Stadium, Jamtha               3
56                              De Beers Diamond Oval               3
57                                       Buffalo Park               3
58                                    OUTsurance Oval               2

In [17]:
# Part C - Question 5
q("""
SELECT match_winner, COUNT(*) AS wins
FROM matches
GROUP BY match_winner
ORDER BY wins DESC;
""")

# My observation:
# This query counts the number of wins for each match winner and sorts them highest first.

                   match_winner  wins
0                Mumbai Indians   155
1           Chennai Super Kings   146
2   Royal Challengers Bangalore   139
3         Kolkata Knight Riders   137
4           Sunrisers Hyderabad   132
5                  Punjab Kings   130
6                Delhi Capitals   126
7              Rajasthan Royals   125
8                Gujarat Titans    42
9          Lucknow Super Giants    33
10       Rising Pune Supergiant    15
11                Pune Warriors    13
12                Gujarat Lions    13
13         Kochi Tuskers Kerala     6

In [18]:
# Part C - Question 6
q("""
SELECT venue, COUNT(*) AS matches_hosted
FROM matches
GROUP BY venue
HAVING COUNT(*) >= 20
ORDER BY matches_hosted DESC;
""")

# My observation:
# HAVING filters grouped results and shows only venues with at least 20 matches.

                                                venue  matches_hosted
0                                        Eden Gardens              77
1                                    Wankhede Stadium              73
2                               M Chinnaswamy Stadium              65
3                                    Feroz Shah Kotla              60
4                            Wankhede Stadium, Mumbai              57
5           Rajiv Gandhi International Stadium, Uppal              49
6                     MA Chidambaram Stadium, Chepauk              48
7                              Sawai Mansingh Stadium              47
8                 Dubai International Cricket Stadium              46
9            MA Chidambaram Stadium, Chepauk, Chennai              38
10                   Narendra Modi Stadium, Ahmedabad              37
11         Punjab Cricket Association Stadium, Mohali              35
12                               Sheikh Zayed Stadium              29
13                            Sharjah Cricket Stadium              28
14                              Eden Gardens, Kolkata              27
15                        Arun Jaitley Stadium, Delhi              27
16  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...              26
17                   M Chinnaswamy Stadium, Bengaluru              24
18  Rajiv Gandhi International Stadium, Uppal, Hyd...              23
19            Maharashtra Cricket Association Stadium              22
20                 Dr DY Patil Sports Academy, Mumbai              20

In [19]:
# Part C - Question 7
q("""
SELECT bowler, COUNT(*) AS deliveries_bowled
FROM deliveries
GROUP BY bowler
HAVING COUNT(*) > 2000
ORDER BY deliveries_bowled DESC;
""")

# My observation:
# This query counts deliveries for each bowler and shows bowlers with more than 2,000 deliveries.

             bowler  deliveries_bowled
0          R Ashwin               4868
1           B Kumar               4596
2         SP Narine               4586
3         RA Jadeja               4261
4         YS Chahal               4068
5         PP Chawla               3895
6         JJ Bumrah               3667
7          AR Patel               3542
8   Harbhajan Singh               3496
9          A Mishra               3444
10      Rashid Khan               3440
11         DJ Bravo               3296
12   Sandeep Sharma               3277
13         UT Yadav               3190
14       SL Malinga               2974
15   Mohammed Shami               2909
16         TA Boult               2871
17   Mohammed Siraj               2652
18          P Kumar               2637
19        KH Pandya               2632
20         HV Patel               2617
21         I Sharma               2546
22        MM Sharma               2471
23       JD Unadkat               2418
24        SN Thakur               2303
25         DW Steyn               2282
26           Z Khan               2276
27    Kuldeep Yadav               2275
28         K Rabada               2214
29    R Vinay Kumar               2186
30        SR Watson               2137
31        IK Pathan               2113
32         CV Varun               2062
33        DL Chahar               2051
34   Arshdeep Singh               2020

In [20]:
# Part D - Question 1
q("""
SELECT COUNT(*) AS missing_city_matches
FROM matches
WHERE city IS NULL;
""")

# My observation:
# IS NULL finds matches where the city value is missing.

   missing_city_matches
0                    51

In [21]:
# Part D - Question 2
q("""
SELECT COUNT(*) AS missing_match_number
FROM matches
WHERE match_number IS NULL;
""")

# My observation:
# This query counts matches where match_number has no value.

   missing_match_number
0                    70

In [22]:
# Part D - Question 3
q("""
SELECT field_pos, LENGTH(field_pos) AS field_pos_length
FROM players
WHERE field_pos IS NOT NULL
ORDER BY field_pos_length DESC;
""")

# My observation:
# LENGTH shows the number of characters in field_pos and helps identify unusually long or suspicious values.

                   field_pos  field_pos_length
0    Occasional Wicketkeeper                23
1    Occasional Wicketkeeper                23
2    Occasional Wicketkeeper                23
3    Occasional Wicketkeeper                23
4    Occasional Wicketkeeper                23
..                       ...               ...
706                                          1
707                                          1
708                                          1
709                                          1
710                                          1

[711 rows x 2 columns]

= NULL is not the correct test because NULL represents a missing or unknown value.
SQL uses IS NULL to check for NULL values.

In [23]:
# Part E - Question 1
q("""
SELECT m.match_id, m.venue, v.city
FROM matches AS m
JOIN venues AS v
ON m.venue = v.venue;
""")

# My observation:
# JOIN combines matching venue records from the matches and venues tables.

,match_id,venue,city
0,335982,M Chinnaswamy Stadium,Bangalore
1,1082591,"Rajiv Gandhi International Stadium, Uppal",Hyderabad
2,1082592,Maharashtra Cricket Association Stadium,Pune
3,1082593,Saurashtra Cricket Association Stadium,Rajkot
4,1082594,Holkar Cricket Stadium,Indore
...,...,...,...
1311,1529282,"Arun Jaitley Stadium, Delhi",Delhi
1312,1529283,Maharaja Yadavindra Singh International Cricke...,New Chandigarh
1313,1529284,"Wankhede Stadium, Mumbai",Mumbai
1314,1529285,"Narendra Modi Stadium, Ahmedabad",Ahmedabad
1315,1529286,"Sawai Mansingh Stadium, Jaipur",Jaipur

In [24]:
# Part E - Question 2
q("""
SELECT d.batter, p.bat_style
FROM deliveries AS d
JOIN players AS p
ON d.batter = p.player_name;
""")

# My observation:
# JOIN connects each batter with the matching player's batting style.

            batter       bat_style
0       MN Samuels  Right hand Bat
1       MN Samuels  Right hand Bat
2       MN Samuels  Right hand Bat
3       MN Samuels  Right hand Bat
4       MN Samuels  Right hand Bat
...            ...             ...
288221      N Rana   Left hand Bat
288222      N Rana   Left hand Bat
288223      N Rana   Left hand Bat
288224   SU Parakh   Left hand Bat
288225   SU Parakh   Left hand Bat

[288226 rows x 2 columns]

In [25]:
# Part E - Question 3
q("""
SELECT DISTINCT d.batter
FROM deliveries AS d
LEFT JOIN players AS p
ON d.batter = p.player_name
WHERE p.player_name IS NULL;
""")

# My observation:
# LEFT JOIN with IS NULL finds batters that do not have a matching record in players.

Empty DataFrame
Columns: [batter]
Index: []

In [26]:
# Part E - Question 4
q("""
SELECT DISTINCT m.venue
FROM matches AS m
LEFT JOIN venues AS v
ON m.venue = v.venue
WHERE v.venue IS NULL;
""")

# My observation:
# This query finds match venues that do not have a matching record in the venues table.

Empty DataFrame
Columns: [venue]
Index: []

In [27]:
# Part F - Question 1
q("""
SELECT match_id, city,
       CASE
           WHEN city IS NULL THEN 'Yes'
           ELSE 'No'
       END AS city_missing
FROM matches;
""")

# My observation:
# CASE WHEN creates city_missing and marks whether the city value is missing.

      match_id            city city_missing
0       335982       Bangalore           No
1      1082591       Hyderabad           No
2      1082592            Pune           No
3      1082593          Rajkot           No
4      1082594          Indore           No
...        ...             ...          ...
1207   1529282           Delhi           No
1208   1529283  New Chandigarh           No
1209   1529284          Mumbai           No
1210   1529285       Ahmedabad           No
1211   1529286          Jaipur           No

[1212 rows x 3 columns]

In [28]:
# Part F - Question 2
q("""
SELECT COUNT(*) AS total_matches,
       SUM(CASE WHEN city IS NULL THEN 1 ELSE 0 END) AS missing_city_matches
FROM matches;
""")

# My observation:
# This query shows the total number of matches and the number of matches with a missing city in one result.

   total_matches  missing_city_matches
0           1212                    51

In [29]:
# Part F - Question 3
q("""
SELECT venue
FROM venues

EXCEPT

SELECT venue
FROM matches;
""")

# My observation:
# EXCEPT finds venues that exist in the venues table but never appear in the matches table.

Empty DataFrame
Columns: [venue]
Index: []

In [31]:
# Part F - Question 4
q("""
SELECT venue
FROM matches

EXCEPT

SELECT venue
FROM venues;
""")

# My observation:
# Reversing EXCEPT finds venues used in matches that are missing from the venues table.

Empty DataFrame
Columns: [venue]
Index: []